### ISSUE TITLE
Small error in Model() function

### ISSUE THREAD

**Issue by RobindeGrootNL** [hf2000510/infectious_disease_modelling#1]
I am trying to adjust the code from your very good TDS blog to a project I am working on, and I ran into a very small issue with your code, nothing groundbreaking, but still improvements never hurt ;).

![image](https://user-images.githubusercontent.com/59803829/80863538-687c5200-8c7d-11ea-9e49-7480202c6c86.png)

Here you can see that generating the variable _t_ should create integers (since it is about days) but due to a small mistake in the np.linspace() function it doesn't.

Changing that part to t = np.linspace(0, days-1, days, dtype=int), solves the issue as you can see below.

![image](https://user-images.githubusercontent.com/59803829/80863560-99f51d80-8c7d-11ea-92be-8d0a5e208e3d.png)

**Comment by henrifroese** [comment]
Thanks, fixed it

**Comment by jswlamb** [comment]
Trying to run your code (part three) in colab and get the following error
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
[<ipython-input-12-b6e2c9adad74>](https://vsue6f4f5-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20220215-060104-RC01_428813935#) in <module>()
----> 1 result = mod.fit(y_data, params, method="least_squares", x=x_data)

3 frames
[<ipython-input-10-02c384c23e59>](https://vsue6f4f5-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20220215-060104-RC01_428813935#) in fitter(x, R_0_start, k, x0, R_0_end, prob_I_to_C, prob_C_to_D, s)
      1 def fitter(x, R_0_start, k, x0, R_0_end, prob_I_to_C, prob_C_to_D, s):
      2     ret = Model(days, agegroups, beds_per_100k, R_0_start, k, x0, R_0_end, prob_I_to_C, prob_C_to_D, s)
----> 3     return ret[6][x]

IndexError: arrays used as indices must be of integer (or boolean) type

Any suggestion how to resolve this? Thx

**Comment by henrifroese** [comment]
Ah weird, should just be
```python
def fitter(x, R_0_start, k, x0, R_0_end, prob_I_to_C, prob_C_to_D, s):
    ret = Model(days, agegroups, beds_per_100k, R_0_start, k, x0, R_0_end, prob_I_to_C, prob_C_to_D, s)
    return ret[6]
```

that works

**Comment by henrifroese** [comment]
I'll change it in the repo soon. As an aside, just looking at the fit the model obviously needs support for several government interventions and seasonality so not too useful nowadays, but I hope it's still useful as an example of how to actually code such a model.
