### ISSUE TITLE
explanation

### ISSUE THREAD

**Issue by Tclack88** [hf2000510/infectious_disease_modelling#2]
Hey, I appreciate your work here.

Sorry, not an "issue" per se. I'm looking at your repo for part3 under the curve fitting, you have this

```
def fitter(x, R_0_start, k, x0, R_0_end, prob_I_to_C, prob_C_to_D, s):
    ret = Model(days, agegroups, beds_per_100k, R_0_start, k, x0, R_0_end, prob_I_to_C, prob_C_to_D, s)
    return ret[6][x]
```

The x isn't really used. I've removed it from `ret[6][x]` so that it's now just `ret[6]` with no change. Other than that, `ret[6]` refers to the 6th returned item of your `Model` function, which is D, deaths. How is that being compared in the scipy lmfit? There's so much mystery in these 3 lines!

**Comment by henrifroese** [comment]
Sorry, only saw this right now; should probably turn notifications on for issues here :bulb: .

The `fitter` is passed to lmfit with `mod = lmfit.Model(fitter)` later on in the code. With lmfit, of course we want to *fit* some data; here we're fitting our model deaths to the real deaths, which you can see in this line: 

`result = mod.fit(y_data, params, method="least_squares", x=x_data)`

y_data are the deaths, x_data is just a vector of x-coordinates [0, ..., n_days]. Internally, lmfit now continuously takes an x value (a day) from the x-coordinates, runs the model, gets the deaths the model predicts for that day through `ret[6][x]` and adjusts the parameters accordingly. That's what the x is for.

Now it seems like you're completely right: as far as I can see, lmfit works vectorized, so it always calls the fitter with all x-coordinates; thus, `ret[6][x]` always just returns all of `ret[6]` and compares it to the whole y-data, so `ret[6][x]` is probably unnecessary.

**Comment by Tclack88** [comment]
Yes, I think at some point last month I figured it out. I was in a bit of a time crunch helping someone with plots with their dissertation work. It's incredible how much more accurate this more complex model was compared to the simple model. I learned so much going through your notebook.
